network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
      optional: true
  wifis:
    wlan0:
      dhcp4: true
      access-points:
        AIRPIXEL:
          password: 34D6MasF8B2M2ws8
          mode: ap
    wlan1:
      dhcp4: true
      optional: true
      access-points:
        "Tomorrow's Flowers":
          password: "If you buy me beers"
          