name: Build Image ISO

on:
  pull_request:
    branches: 
      - master

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Qemu-User-Static
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: test
        run: docker run arm64v8/python@sha256:9ced67c06852b84c047a38374865b523c909095a0dbef2c871a859e43f0ac5eb echo hi
